name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build foundationdb4s
    runs-on: ubuntu-latest
    steps:
      - name: Install FDB
        run: |
          sudo apt update && \
          sudo apt -qq -y install wget && \
          wget https://www.foundationdb.org/downloads/6.3.18/ubuntu/installers/foundationdb-clients_6.3.18-1_amd64.deb && \
          wget https://www.foundationdb.org/downloads/6.3.18/ubuntu/installers/foundationdb-server_6.3.18-1_amd64.deb && \
          sudo dpkg -i foundationdb-clients_6.3.18-1_amd64.deb foundationdb-server_6.3.18-1_amd64.deb
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: Build and Test
        run: sbt -v test:scalafmt scalafmtSbt coverage +test coverageReport
